#!/usr/bin/env php
<?php

echo "\nbuild chars ...";
exec('php '.__DIR__.'/chars_gen');
echo "Done.";

echo "\nbuild words ...";
exec('php '.__DIR__.'/words_gen');
echo "Done.";

echo "\nbuild combine ...";
exec('cat '.__DIR__.'/chars.dat >> '.__DIR__.'/words.dat');
echo "Done.";
$words = [];
$lines = file(__DIR__.'/words.dat');

foreach ($lines as $line) {
    list($word, $pinyin) = explode(",", trim($line));

    $words[$word] = "\t{$pinyin}\t";
}

$file = realpath(__DIR__.'/../data/words.dat');
file_put_contents($file, "<?php \n return ".var_export($words, true).';');

exec('rm -rf '.__DIR__.'/*.dat');

echo "\nDictionary is saved in path: $file!";