#!/usr/bin/env php
<?php

echo "cleaning ...\n";
exec('rm -rf '.__DIR__.'/../data/*');

echo "build chars ...\n";
exec('php '.__DIR__.'/chars_gen');

echo "build words ...\n";
exec('php '.__DIR__.'/words_gen');

echo "build combine ...\n";
exec('cat '.__DIR__.'/../data/chars.dat >> '.__DIR__.'/../data/words.dat');
exec('rm -rf '.__DIR__.'/../data/chars.dat');

echo "Done!\n";